name: "Java Runner"
description: "Compile and run Java program"

outputs:
  output:
    description: "Output of the Java program"
    value: ${{ steps.run-java.outputs.output }}

runs:
  using: "composite"
  steps:
    - name: Compile Java File
      shell: bash
      run: javac Main.java

    - name: Run Java Program
      id: run-java
      shell: bash
      run: echo "output=$(java Main)" >> $GITHUB_OUTPUT