name: output Example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Custom Action
      id: custom-action
      uses: ./.github/actions/java-build

    - name: Print Output
      run: echo "Output: ${{ steps.custom-action.outputs.output }}"